export type PlanTier = "free" | "growth" | "professional" | "enterprise";

export type PlanLimitsJson = {
  // Household-focused
  maxMealPlans: number;
  maxGroceryListsPerMonth: number;
  maxHouseholdMembers: number;
  maxSavedRestaurants: number;
  maxChefRequestsPerMonth: number;
  chefMarketplaceEnabled: boolean;
  groceryExportsEnabled: boolean;
  restaurantFallbackEnabled: boolean;
  // Seller-focused (-1 = unlimited, 0 = not applicable / blocked)
  maxMenuItems: number;          // restaurant + catering MenuItem count
  maxActiveServices: number;     // chef ChefService (isActive=true) count
  maxLocations: number;          // multi-location support cap
  maxStaffMembers: number;       // Membership count cap
  maxOrdersPerMonth: number;     // food order acceptances / month (restaurant + catering)
  maxBookingsPerMonth: number;   // HomeChefRequestOffer acceptances / month (chef)
};

export type PlanDefinition = {
  slug: string;
  name: string;
  tier: PlanTier;
  planAudience: "household" | "chef_staff" | "home_catering" | "restaurant" | "platform_internal";
  billingInterval: "monthly" | "yearly" | "custom";
  priceAmount: number;
  currencyCode: string;
  isPopular: boolean;
  status: "active" | "draft";
  stripePriceId: string | null;
  description: string;
  featuresJson: string[];
  limitsJson: PlanLimitsJson;
};

export const PLAN_CATALOG: PlanDefinition[] = [
  // ── HOUSEHOLD ─────────────────────────────────────────────────────────────
  // Forever free — no paid tiers, no Stripe, no billing toggle needed
  {
    slug: "household-free",
    name: "Household",
    tier: "free",
    planAudience: "household",
    billingInterval: "monthly",
    priceAmount: 0,
    currencyCode: "USD",
    isPopular: false,
    status: "active",
    stripePriceId: null,
    description: "Full household meal planning, grocery lists, and food discovery — forever free.",
    featuresJson: [
      "Unlimited recipes & meal plans",
      "Smart grocery list generation",
      "Unlimited household members",
      "Save restaurants, chefs & caterers",
      "Place food orders",
      "Recipe favorites & collections",
    ],
    limitsJson: {
      maxMealPlans: -1,
      maxGroceryListsPerMonth: -1,
      maxHouseholdMembers: -1,
      maxSavedRestaurants: -1,
      maxChefRequestsPerMonth: -1,
      chefMarketplaceEnabled: true,
      groceryExportsEnabled: true,
      restaurantFallbackEnabled: true,
      maxMenuItems: 0,
      maxActiveServices: 0,
      maxLocations: 0,
      maxStaffMembers: 0,
      maxOrdersPerMonth: 0,
      maxBookingsPerMonth: 0,
    },
  },

  // ── HOME CHEF ─────────────────────────────────────────────────────────────
  {
    slug: "home-chef-free",
    name: "Chef Free",
    tier: "free",
    planAudience: "chef_staff",
    billingInterval: "monthly",
    priceAmount: 0,
    currencyCode: "USD",
    isPopular: false,
    status: "active",
    stripePriceId: null,
    description: "Start your home chef business with a public profile and core request tools.",
    featuresJson: [
      "Public chef profile",
      "Accept home chef requests",
      "Order inbox & management",
      "Platform marketplace listing",
    ],
    limitsJson: {
      maxMealPlans: 0,
      maxGroceryListsPerMonth: 0,
      maxHouseholdMembers: 1,
      maxSavedRestaurants: 0,
      maxChefRequestsPerMonth: -1,
      chefMarketplaceEnabled: true,
      groceryExportsEnabled: false,
      restaurantFallbackEnabled: false,
      maxMenuItems: 5,
      maxActiveServices: 1,
      maxLocations: 1,
      maxStaffMembers: 1,
      maxOrdersPerMonth: 0,
      maxBookingsPerMonth: 20,
    },
  },
  {
    slug: "home-chef-growth-monthly",
    name: "Chef Growth",
    tier: "growth",
    planAudience: "chef_staff",
    billingInterval: "monthly",
    priceAmount: 29,
    currencyCode: "USD",
    isPopular: true,
    status: "active",
    stripePriceId: null,
    description: "Everything you need to grow a thriving home chef business.",
    featuresJson: [
      "Everything in Free",
      "Priority marketplace placement",
      "Advanced order management",
      "Customer messaging",
      "Analytics & earnings reports",
      "Priority support",
    ],
    limitsJson: {
      maxMealPlans: 0,
      maxGroceryListsPerMonth: 0,
      maxHouseholdMembers: 1,
      maxSavedRestaurants: 0,
      maxChefRequestsPerMonth: -1,
      chefMarketplaceEnabled: true,
      groceryExportsEnabled: true,
      restaurantFallbackEnabled: false,
      maxMenuItems: -1,
      maxActiveServices: -1,
      maxLocations: 1,
      maxStaffMembers: 0,
      maxOrdersPerMonth: 0,
      maxBookingsPerMonth: 150,
    },
  },
  {
    slug: "home-chef-growth-yearly",
    name: "Chef Growth",
    tier: "growth",
    planAudience: "chef_staff",
    billingInterval: "yearly",
    priceAmount: 278.40,
    currencyCode: "USD",
    isPopular: true,
    status: "active",
    stripePriceId: null,
    description: "Everything you need to grow a thriving home chef business.",
    featuresJson: [
      "Everything in Free",
      "Priority marketplace placement",
      "Advanced order management",
      "Customer messaging",
      "Analytics & earnings reports",
      "Priority support",
    ],
    limitsJson: {
      maxMealPlans: 0,
      maxGroceryListsPerMonth: 0,
      maxHouseholdMembers: 1,
      maxSavedRestaurants: 0,
      maxChefRequestsPerMonth: -1,
      chefMarketplaceEnabled: true,
      groceryExportsEnabled: true,
      restaurantFallbackEnabled: false,
      maxMenuItems: -1,
      maxActiveServices: -1,
      maxLocations: 1,
      maxStaffMembers: 0,
      maxOrdersPerMonth: 0,
      maxBookingsPerMonth: 150,
    },
  },
  {
    slug: "home-chef-professional-monthly",
    name: "Chef Professional",
    tier: "professional",
    planAudience: "chef_staff",
    billingInterval: "monthly",
    priceAmount: 79,
    currencyCode: "USD",
    isPopular: false,
    status: "active",
    stripePriceId: null,
    description: "Professional tools for established home chefs at scale.",
    featuresJson: [
      "Everything in Growth",
      "Multi-menu management",
      "Payout acceleration",
      "Advanced analytics",
      "Bulk order management",
      "Dedicated account support",
    ],
    limitsJson: {
      maxMealPlans: 0,
      maxGroceryListsPerMonth: 0,
      maxHouseholdMembers: 1,
      maxSavedRestaurants: 0,
      maxChefRequestsPerMonth: -1,
      chefMarketplaceEnabled: true,
      groceryExportsEnabled: true,
      restaurantFallbackEnabled: false,
      maxMenuItems: -1,
      maxActiveServices: -1,
      maxLocations: 1,
      maxStaffMembers: 10,
      maxOrdersPerMonth: 0,
      maxBookingsPerMonth: -1,
    },
  },
  {
    slug: "home-chef-professional-yearly",
    name: "Chef Professional",
    tier: "professional",
    planAudience: "chef_staff",
    billingInterval: "yearly",
    priceAmount: 758.40,
    currencyCode: "USD",
    isPopular: false,
    status: "active",
    stripePriceId: null,
    description: "Professional tools for established home chefs at scale.",
    featuresJson: [
      "Everything in Growth",
      "Multi-menu management",
      "Payout acceleration",
      "Advanced analytics",
      "Bulk order management",
      "Dedicated account support",
    ],
    limitsJson: {
      maxMealPlans: 0,
      maxGroceryListsPerMonth: 0,
      maxHouseholdMembers: 1,
      maxSavedRestaurants: 0,
      maxChefRequestsPerMonth: -1,
      chefMarketplaceEnabled: true,
      groceryExportsEnabled: true,
      restaurantFallbackEnabled: false,
      maxMenuItems: -1,
      maxActiveServices: -1,
      maxLocations: 1,
      maxStaffMembers: 10,
      maxOrdersPerMonth: 0,
      maxBookingsPerMonth: -1,
    },
  },
  {
    slug: "home-chef-enterprise",
    name: "Chef Enterprise",
    tier: "enterprise",
    planAudience: "chef_staff",
    billingInterval: "custom",
    priceAmount: 0,
    currencyCode: "USD",
    isPopular: false,
    status: "active",
    stripePriceId: null,
    description: "Custom terms for culinary businesses and brand partnerships.",
    featuresJson: [
      "Everything in Professional",
      "Custom contract terms",
      "Dedicated account manager",
      "White-glove onboarding",
      "SLA guarantees",
    ],
    limitsJson: {
      maxMealPlans: -1,
      maxGroceryListsPerMonth: -1,
      maxHouseholdMembers: -1,
      maxSavedRestaurants: -1,
      maxChefRequestsPerMonth: -1,
      chefMarketplaceEnabled: true,
      groceryExportsEnabled: true,
      restaurantFallbackEnabled: false,
      maxMenuItems: -1,
      maxActiveServices: -1,
      maxLocations: -1,
      maxStaffMembers: -1,
      maxOrdersPerMonth: 0,
      maxBookingsPerMonth: -1,
    },
  },

  // ── HOME CATERING ─────────────────────────────────────────────────────────
  {
    slug: "catering-free",
    name: "Catering Free",
    tier: "free",
    planAudience: "home_catering",
    billingInterval: "monthly",
    priceAmount: 0,
    currencyCode: "USD",
    isPopular: false,
    status: "active",
    stripePriceId: null,
    description: "Launch your catering operation with a public profile and core order tools.",
    featuresJson: [
      "Public catering profile",
      "Accept catering orders",
      "Menu management",
      "Order inbox & management",
    ],
    limitsJson: {
      maxMealPlans: 5,
      maxGroceryListsPerMonth: 5,
      maxHouseholdMembers: 2,
      maxSavedRestaurants: 5,
      maxChefRequestsPerMonth: 0,
      chefMarketplaceEnabled: false,
      groceryExportsEnabled: false,
      restaurantFallbackEnabled: false,
      maxMenuItems: 5,
      maxActiveServices: 0,
      maxLocations: 1,
      maxStaffMembers: 0,
      maxOrdersPerMonth: 10,
      maxBookingsPerMonth: 0,
    },
  },
  {
    slug: "catering-growth-monthly",
    name: "Catering Growth",
    tier: "growth",
    planAudience: "home_catering",
    billingInterval: "monthly",
    priceAmount: 69,
    currencyCode: "USD",
    isPopular: true,
    status: "active",
    stripePriceId: null,
    description: "Scale your catering business with advanced tools and priority marketplace placement.",
    featuresJson: [
      "Everything in Free",
      "Priority marketplace placement",
      "Advanced order management",
      "Customer messaging",
      "Analytics & revenue reports",
      "Priority support",
    ],
    limitsJson: {
      maxMealPlans: 10,
      maxGroceryListsPerMonth: 20,
      maxHouseholdMembers: 8,
      maxSavedRestaurants: 20,
      maxChefRequestsPerMonth: 0,
      chefMarketplaceEnabled: false,
      groceryExportsEnabled: true,
      restaurantFallbackEnabled: false,
      maxMenuItems: -1,
      maxActiveServices: 0,
      maxLocations: 1,
      maxStaffMembers: 0,
      maxOrdersPerMonth: -1,
      maxBookingsPerMonth: 0,
    },
  },
  {
    slug: "catering-growth-yearly",
    name: "Catering Growth",
    tier: "growth",
    planAudience: "home_catering",
    billingInterval: "yearly",
    priceAmount: 662.40,
    currencyCode: "USD",
    isPopular: true,
    status: "active",
    stripePriceId: null,
    description: "Scale your catering business with advanced tools and priority marketplace placement.",
    featuresJson: [
      "Everything in Free",
      "Priority marketplace placement",
      "Advanced order management",
      "Customer messaging",
      "Analytics & revenue reports",
      "Priority support",
    ],
    limitsJson: {
      maxMealPlans: 10,
      maxGroceryListsPerMonth: 20,
      maxHouseholdMembers: 8,
      maxSavedRestaurants: 20,
      maxChefRequestsPerMonth: 0,
      chefMarketplaceEnabled: false,
      groceryExportsEnabled: true,
      restaurantFallbackEnabled: false,
      maxMenuItems: -1,
      maxActiveServices: 0,
      maxLocations: 1,
      maxStaffMembers: 0,
      maxOrdersPerMonth: -1,
      maxBookingsPerMonth: 0,
    },
  },
  {
    slug: "catering-professional-monthly",
    name: "Catering Professional",
    tier: "professional",
    planAudience: "home_catering",
    billingInterval: "monthly",
    priceAmount: 179,
    currencyCode: "USD",
    isPopular: false,
    status: "active",
    stripePriceId: null,
    description: "Enterprise-grade catering management for high-volume operations.",
    featuresJson: [
      "Everything in Growth",
      "Multi-location support",
      "Payout acceleration",
      "Advanced reporting",
      "Staff accounts",
      "Dedicated account manager",
    ],
    limitsJson: {
      maxMealPlans: -1,
      maxGroceryListsPerMonth: -1,
      maxHouseholdMembers: 15,
      maxSavedRestaurants: -1,
      maxChefRequestsPerMonth: 0,
      chefMarketplaceEnabled: false,
      groceryExportsEnabled: true,
      restaurantFallbackEnabled: false,
      maxMenuItems: -1,
      maxActiveServices: 0,
      maxLocations: 3,
      maxStaffMembers: 10,
      maxOrdersPerMonth: -1,
      maxBookingsPerMonth: 0,
    },
  },
  {
    slug: "catering-professional-yearly",
    name: "Catering Professional",
    tier: "professional",
    planAudience: "home_catering",
    billingInterval: "yearly",
    priceAmount: 1718.40,
    currencyCode: "USD",
    isPopular: false,
    status: "active",
    stripePriceId: null,
    description: "Enterprise-grade catering management for high-volume operations.",
    featuresJson: [
      "Everything in Growth",
      "Multi-location support",
      "Payout acceleration",
      "Advanced reporting",
      "Staff accounts",
      "Dedicated account manager",
    ],
    limitsJson: {
      maxMealPlans: -1,
      maxGroceryListsPerMonth: -1,
      maxHouseholdMembers: 15,
      maxSavedRestaurants: -1,
      maxChefRequestsPerMonth: 0,
      chefMarketplaceEnabled: false,
      groceryExportsEnabled: true,
      restaurantFallbackEnabled: false,
      maxMenuItems: -1,
      maxActiveServices: 0,
      maxLocations: 3,
      maxStaffMembers: 10,
      maxOrdersPerMonth: -1,
      maxBookingsPerMonth: 0,
    },
  },
  {
    slug: "catering-enterprise",
    name: "Catering Enterprise",
    tier: "enterprise",
    planAudience: "home_catering",
    billingInterval: "custom",
    priceAmount: 0,
    currencyCode: "USD",
    isPopular: false,
    status: "active",
    stripePriceId: null,
    description: "Custom terms for large catering companies and multi-location operations.",
    featuresJson: [
      "Everything in Professional",
      "Custom contract terms",
      "Dedicated account manager",
      "White-glove onboarding",
      "SLA guarantees",
    ],
    limitsJson: {
      maxMealPlans: -1,
      maxGroceryListsPerMonth: -1,
      maxHouseholdMembers: -1,
      maxSavedRestaurants: -1,
      maxChefRequestsPerMonth: -1,
      chefMarketplaceEnabled: true,
      groceryExportsEnabled: true,
      restaurantFallbackEnabled: true,
      maxMenuItems: -1,
      maxActiveServices: 0,
      maxLocations: -1,
      maxStaffMembers: -1,
      maxOrdersPerMonth: -1,
      maxBookingsPerMonth: 0,
    },
  },

  // ── RESTAURANT ────────────────────────────────────────────────────────────
  {
    slug: "restaurant-free",
    name: "Restaurant Free",
    tier: "free",
    planAudience: "restaurant",
    billingInterval: "monthly",
    priceAmount: 0,
    currencyCode: "USD",
    isPopular: false,
    status: "active",
    stripePriceId: null,
    description: "Get your restaurant listed and start accepting orders.",
    featuresJson: [
      "Restaurant profile & listing",
      "Menu builder",
      "Accept food orders",
      "Location & map listing",
    ],
    limitsJson: {
      maxMealPlans: 2,
      maxGroceryListsPerMonth: 5,
      maxHouseholdMembers: 3,
      maxSavedRestaurants: -1,
      maxChefRequestsPerMonth: 0,
      chefMarketplaceEnabled: false,
      groceryExportsEnabled: false,
      restaurantFallbackEnabled: true,
      maxMenuItems: 25,
      maxActiveServices: 0,
      maxLocations: 1,
      maxStaffMembers: 0,
      maxOrdersPerMonth: 50,
      maxBookingsPerMonth: 0,
    },
  },
  {
    slug: "restaurant-growth-monthly",
    name: "Restaurant Growth",
    tier: "growth",
    planAudience: "restaurant",
    billingInterval: "monthly",
    priceAmount: 59,
    currencyCode: "USD",
    isPopular: true,
    status: "active",
    stripePriceId: null,
    description: "Grow your restaurant with advanced ordering, analytics, and priority visibility.",
    featuresJson: [
      "Everything in Free",
      "Priority search placement",
      "Advanced order management",
      "Customer messaging",
      "Analytics & sales reports",
      "Priority support",
    ],
    limitsJson: {
      maxMealPlans: 5,
      maxGroceryListsPerMonth: 10,
      maxHouseholdMembers: 5,
      maxSavedRestaurants: -1,
      maxChefRequestsPerMonth: 0,
      chefMarketplaceEnabled: false,
      groceryExportsEnabled: false,
      restaurantFallbackEnabled: true,
      maxMenuItems: -1,
      maxActiveServices: 0,
      maxLocations: 1,
      maxStaffMembers: 0,
      maxOrdersPerMonth: -1,
      maxBookingsPerMonth: 0,
    },
  },
  {
    slug: "restaurant-growth-yearly",
    name: "Restaurant Growth",
    tier: "growth",
    planAudience: "restaurant",
    billingInterval: "yearly",
    priceAmount: 566.40,
    currencyCode: "USD",
    isPopular: true,
    status: "active",
    stripePriceId: null,
    description: "Grow your restaurant with advanced ordering, analytics, and priority visibility.",
    featuresJson: [
      "Everything in Free",
      "Priority search placement",
      "Advanced order management",
      "Customer messaging",
      "Analytics & sales reports",
      "Priority support",
    ],
    limitsJson: {
      maxMealPlans: 5,
      maxGroceryListsPerMonth: 10,
      maxHouseholdMembers: 5,
      maxSavedRestaurants: -1,
      maxChefRequestsPerMonth: 0,
      chefMarketplaceEnabled: false,
      groceryExportsEnabled: false,
      restaurantFallbackEnabled: true,
      maxMenuItems: -1,
      maxActiveServices: 0,
      maxLocations: 1,
      maxStaffMembers: 0,
      maxOrdersPerMonth: -1,
      maxBookingsPerMonth: 0,
    },
  },
  {
    slug: "restaurant-professional-monthly",
    name: "Restaurant Professional",
    tier: "professional",
    planAudience: "restaurant",
    billingInterval: "monthly",
    priceAmount: 149,
    currencyCode: "USD",
    isPopular: false,
    status: "active",
    stripePriceId: null,
    description: "Full-featured restaurant management for established operations.",
    featuresJson: [
      "Everything in Growth",
      "Multi-menu management",
      "Staff accounts",
      "Payout acceleration",
      "Advanced reporting",
      "Dedicated account manager",
    ],
    limitsJson: {
      maxMealPlans: -1,
      maxGroceryListsPerMonth: -1,
      maxHouseholdMembers: 15,
      maxSavedRestaurants: -1,
      maxChefRequestsPerMonth: 0,
      chefMarketplaceEnabled: false,
      groceryExportsEnabled: false,
      restaurantFallbackEnabled: true,
      maxMenuItems: -1,
      maxActiveServices: 0,
      maxLocations: 3,
      maxStaffMembers: 10,
      maxOrdersPerMonth: -1,
      maxBookingsPerMonth: 0,
    },
  },
  {
    slug: "restaurant-professional-yearly",
    name: "Restaurant Professional",
    tier: "professional",
    planAudience: "restaurant",
    billingInterval: "yearly",
    priceAmount: 1430.40,
    currencyCode: "USD",
    isPopular: false,
    status: "active",
    stripePriceId: null,
    description: "Full-featured restaurant management for established operations.",
    featuresJson: [
      "Everything in Growth",
      "Multi-menu management",
      "Staff accounts",
      "Payout acceleration",
      "Advanced reporting",
      "Dedicated account manager",
    ],
    limitsJson: {
      maxMealPlans: -1,
      maxGroceryListsPerMonth: -1,
      maxHouseholdMembers: 15,
      maxSavedRestaurants: -1,
      maxChefRequestsPerMonth: 0,
      chefMarketplaceEnabled: false,
      groceryExportsEnabled: false,
      restaurantFallbackEnabled: true,
      maxMenuItems: -1,
      maxActiveServices: 0,
      maxLocations: 3,
      maxStaffMembers: 10,
      maxOrdersPerMonth: -1,
      maxBookingsPerMonth: 0,
    },
  },
  {
    slug: "restaurant-enterprise",
    name: "Restaurant Enterprise",
    tier: "enterprise",
    planAudience: "restaurant",
    billingInterval: "custom",
    priceAmount: 0,
    currencyCode: "USD",
    isPopular: false,
    status: "active",
    stripePriceId: null,
    description: "Custom contract for restaurant groups, chains, and enterprise food operators.",
    featuresJson: [
      "Everything in Professional",
      "Multi-location management",
      "Custom contract terms",
      "Dedicated account manager",
      "White-glove onboarding",
      "SLA guarantees",
    ],
    limitsJson: {
      maxMealPlans: -1,
      maxGroceryListsPerMonth: -1,
      maxHouseholdMembers: -1,
      maxSavedRestaurants: -1,
      maxChefRequestsPerMonth: -1,
      chefMarketplaceEnabled: false,
      groceryExportsEnabled: true,
      restaurantFallbackEnabled: true,
      maxMenuItems: -1,
      maxActiveServices: 0,
      maxLocations: -1,
      maxStaffMembers: -1,
      maxOrdersPerMonth: -1,
      maxBookingsPerMonth: 0,
    },
  },

  // ── INTERNAL ──────────────────────────────────────────────────────────────
  {
    slug: "enterprise-internal",
    name: "Enterprise / Internal",
    tier: "enterprise",
    planAudience: "platform_internal",
    billingInterval: "custom",
    priceAmount: 0,
    currencyCode: "USD",
    isPopular: false,
    status: "draft",
    stripePriceId: null,
    description: "Internal platform plan for administrative, enterprise, and manually contracted accounts.",
    featuresJson: ["All features", "Custom limits", "Country-level configuration", "Internal administration"],
    limitsJson: {
      maxMealPlans: -1,
      maxGroceryListsPerMonth: -1,
      maxHouseholdMembers: -1,
      maxSavedRestaurants: -1,
      maxChefRequestsPerMonth: -1,
      chefMarketplaceEnabled: true,
      groceryExportsEnabled: true,
      restaurantFallbackEnabled: true,
      maxMenuItems: -1,
      maxActiveServices: -1,
      maxLocations: -1,
      maxStaffMembers: -1,
      maxOrdersPerMonth: -1,
      maxBookingsPerMonth: -1,
    },
  },
];

// Old slugs from the pre-Phase-1 catalog. Archive these during re-seed so they
// no longer appear publicly. Slugs must stay in the DB for historical data integrity.
export const LEGACY_PLAN_SLUGS = [
  "free",
  "family-plus",
  "household-premium",
  "premium-household",
  "home-chef-basic",
  "home-chef-plus",
  "home-chef-pro",
  "chef-business",
  "catering-starter",
  "catering-pro",
  "home-catering-seller",
  "restaurant-partner",
  "restaurant-growth",
  "enterprise",
];
